ALTER TABLE approvals ADD COLUMN IF NOT EXISTS rejected_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE approvals ADD COLUMN IF NOT EXISTS rejected_by VARCHAR(140);
ALTER TABLE approvals ADD COLUMN IF NOT EXISTS rejection_reason TEXT;
